In [1]:
# Import Libraries

In [1]:
import pandas as pd
import numpy as np

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [2]:
movies=pd.read_csv(r'C:\Users\lenovo\Desktop\ironhack\Labs\DAFT_212\module_2\Lab_5_ Pivot-Tables-and-Crosstab\movie_metadata.csv')

In [3]:
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

### 2. Use crosstabs to show the number of movies per country

In [5]:
pd.crosstab(index=movies.genres,columns=movies.country,margins=True)

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany,All
genres,,,,,,,,,,,,,,,,,,,,,
Action,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,8,0,0,11
Action|Adventure,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,9,0,0,11
Action|Adventure|Animation|Comedy|Crime|Family|Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Action|Adventure|Animation|Comedy|Drama|Family|Fantasy|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,4,12,0,0,20
Thriller|War,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Thriller|Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,7,0,0,12
All,1,4,1,55,1,4,8,1,1,1,...,6,3,2,5,1,448,3807,1,3,5038

In [6]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [7]:
pd.crosstab(index=[movies['director_name'],movies['genres']],columns=movies['country'])

,country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
director_name,genres,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Action|Adventure|Comedy|Fantasy|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Hann,Drama|Horror|Mystery|Sci-Fi|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Schneider,Drama|Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Seltzer,Comedy|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Abel Ferrara,Crime|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,Comedy|Music|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Álex de la Iglesia,Crime|Mystery|Thriller,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Émile Gaudreault,Comedy|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Éric Tessier,Action|Drama|Horror|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Étienne Faure,Drama|Musical|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
pd.crosstab(index=movies['genres'],columns=movies['country'])

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
genres,,,,,,,,,,,,,,,,,,,,,
Action,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,8,0,0
Action|Adventure,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,9,0,0
Action|Adventure|Animation|Comedy|Crime|Family|Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Action|Adventure|Animation|Comedy|Drama|Family|Fantasy|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sci-Fi|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,9,0,0
Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,12,0,0
Thriller|War,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Thriller|Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,7,0,0

### 4. Average duration of filmes grouped by color

In [24]:
pd.crosstab(movies.genres, movies.color,values=movies['duration'],aggfunc='mean')

color,Black and White,Color
genres,,
Action,111.0,107.444444
Action|Adventure,NaN,112.636364
Action|Adventure|Animation|Comedy|Crime|Family|Fantasy,NaN,95.000000
Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi,NaN,96.000000
Action|Adventure|Animation|Comedy|Family,NaN,91.500000
...,...,...
Sci-Fi|Thriller,NaN,104.700000
Thriller,NaN,103.350000
Thriller|War,133.0,NaN
Thriller|Western,85.0,NaN
Western,NaN,106.000000

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [26]:
movies['films_like']=movies['actor_1_facebook_likes']+movies['actor_3_facebook_likes']+movies['actor_2_facebook_likes']

In [31]:
pop_directors=pd.crosstab(movies.director_name,columns='likes',values=movies.films_like,aggfunc="mean")

In [32]:
pop_directors.sort_values(by='likes',ascending=False)

col_0                likes
director_name
Travis Romero     283000.0
Johnny Remo       261875.0
John Gulager      166898.0
Adam McKay        129828.0
Andrew Douglas    120000.0
...                    ...
Blaz Zavrsnik          0.0
Benjamin Roberds       0.0
Khyentse Norbu         0.0
Lisanne Pajot          0.0
Catherine Gund         0.0

[2385 rows x 1 columns]

In [34]:
movies.loc[movies.director_name=='Johnny Remo']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,films_like
4592,Color,Johnny Remo,2.0,112.0,74.0,891.0,Randy Wayne,260000.0,96734.0,Action|Drama,...,English,USA,PG-13,1000000.0,2012.0,984.0,5.6,1.85,706,261875.0